languageCode = "en"
languageName = "English"
weight = 1
title = "Airports Guide"

[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "Jan 2, 2006"
  description = "Airports Guide - Travel Blog"
